### ISSUE TITLE
gram-cam issue 

### ISSUE THREAD

**Issue by Jorewang** [frgfm/torch-cam#9] opened 2020-07-01 09:11 UTC
When I run cam_example.py with grad-cam, i get following issue, please tell me how to fix it?

![1](https://user-images.githubusercontent.com/22468345/86226160-d41b6680-bbbd-11ea-8233-6fcf47f4067c.png)

**Comment by frgfm** [comment] 2020-07-09 14:55
Hi there @Jorewang,

Thanks for reporting this! I am not able to reproduce this error so far. Would you mind:
- specifying whether you use different values for script arguments than the default ones
- specifying your setup (which you can do by running this [script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py) for instance, and pasting the result in your reply)

**Comment by frgfm** [comment] 2020-08-26 13:31
Any update @Jorewang?

**Comment by frgfm** [comment] 2020-09-07 14:28
Closing this for now, feel free to reopen if you encounter this issue again!

**Closed by frgfm** 2020-09-07 14:28 UTC
Labels: module: scripts, question

**Comment by zhangpanPP** [comment] 2020-11-12 10:05
When I run cam_example.py with grad-cam, i get following issue that self.hook_g is None, please tell me how to fix it?
![image](https://user-images.githubusercontent.com/44059900/98925919-95090480-2511-11eb-87e7-eb8b7778449d.png)
