### ISSUE TITLE
self.hook_g is None

### ISSUE THREAD

**Issue by zhangpanPP** [frgfm/torch-cam#22] opened 2020-11-12 10:06 UTC
When I run cam_example.py with grad-cam, i get following issue that self.hook_g is None, please tell me how to fix it?
![image](https://user-images.githubusercontent.com/44059900/98926113-d699af80-2511-11eb-8926-6adcc6d8ff3a.png)

**Comment by frgfm** [comment] 2020-11-12 14:01
Hi there @zhangpanPP,

Thanks for reporting that! I indeed encountered the same issue and found the root cause: using default attribute inheritance, some hook handles were cleared by other extractors, which is wrong. This issue can only be seen if you have different extractors on the same model. This should be fixed now in #23 

Let me know if you still have issues!

**Closed** 2020-11-12 14:00 UTC
Labels: bug
